#!/usr/bin/env node
// Regenerates src/preview/data.js, the 1200x630 card that link previews (Telegram, Slack, Discord, X,
// iMessage ...) show for the sign-in page, served at /auth/preview-<hash>.png.
//
// Needs Playwright with Chromium (npx playwright install chromium, or PLAYWRIGHT_BROWSERS_PATH). The output is
// committed, so nothing here runs when the package is installed or used. It draws the card from the bundled
// fonts and the page's own accent and ink, so re-run it when either changes.
import { chromium } from "playwright";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { DEFAULT_BRANDING } from "../src/login-page.js";
import { fontFaceCss } from "../src/fonts/index.js";
import { FONT_DATA } from "../src/fonts/data.js";

const PLANE = "M21.4 3.6 2.9 10.8c-1 .4-1 1.8.1 2.1l4.6 1.5 1.8 5.6c.3.9 1.4 1.1 2 .4l2.6-2.7 4.8 3.5c.8.6 1.9.1 2.1-.9l3-15.1c.2-1.1-.8-2-1.9-1.6Zm-3.6 4.1-8.5 7.6-.4 3.4-1.2-4 9.6-6.9c.4-.3.9.2.5.6Z";
const accent = DEFAULT_BRANDING.accent;

// The fonts are inlined as data: URIs: the card is drawn offline.
const faces = fontFaceCss("/f").replace(/url\("\/f\/([^"]+?)-[0-9a-f]{8}\.woff2"\)/g, (_, file) => `url("data:font/woff2;base64,${FONT_DATA[file]}")`);

const html = `<!doctype html><meta charset="utf-8"><style>
${faces}
* { box-sizing: border-box; margin: 0; }
body { width: 1200px; height: 630px; overflow: hidden; background-color: ${accent}; color: #17130f;
  background-image: radial-gradient(rgba(23,19,15,.24) 1.4px, transparent 2px); background-size: 28px 28px;
  font: 500 30px/1.3 "TQA Sans", sans-serif; -webkit-font-smoothing: antialiased; position: relative; }
.mark { position: absolute; left: 72px; top: 64px; display: flex; align-items: center; gap: 18px; font-weight: 700; font-size: 30px; }
.mark i { width: 64px; height: 64px; border-radius: 16px; background: #17130f; display: grid; place-items: center; }
.mark svg { width: 34px; height: 34px; fill: ${accent}; }
h1 { position: absolute; left: 72px; top: 150px; font: 900 128px/.94 "TQA Display", sans-serif; letter-spacing: -.01em; text-transform: uppercase; }
.ticket { position: absolute; left: 72px; right: 72px; bottom: 56px; height: 128px; white-space: nowrap; background: #fbfaf6; border-radius: 22px;
  box-shadow: 0 0 0 3px #17130f, 0 24px 40px -18px rgba(0,0,0,.45); display: flex; align-items: center; padding: 0 44px; gap: 52px; }
.ticket .f { font: 500 20px/1 "TQA Mono", monospace; letter-spacing: .14em; text-transform: uppercase; color: #6a6358; }
.ticket b { display: block; margin-top: 12px; font: 600 32px/1 "TQA Sans", sans-serif; letter-spacing: 0; text-transform: none; color: #17130f; }
.ticket .sp { flex: 1; }
.ticket .go { display: flex; align-items: center; gap: 14px; background: #17130f; color: #fff; border-radius: 999px; padding: 18px 30px; font: 700 28px/1 "TQA Sans", sans-serif; }
.ticket .go svg { width: 30px; height: 30px; fill: ${accent}; }
</style>
<div class="mark"><i><svg viewBox="0 0 24 24"><path d="${PLANE}"/></svg></i>Authentication platform</div>
<h1>Sign in with<br>Telegram.</h1>
<div class="ticket">
  <div class="f">Password<b>None</b></div>
  <div class="f">Phone number<b>Not needed</b></div>
  <div class="f">Code to type<b>None</b></div>
  <div class="sp"></div>
  <div class="go"><svg viewBox="0 0 24 24"><path d="${PLANE}"/></svg>Secure sign-in</div>
</div>`;

const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined });
const page = await browser.newPage({ viewport: { width: 1200, height: 630 }, deviceScaleFactor: 1 });
await page.setContent(html);
await page.evaluate(() => document.fonts.ready);
const png = await page.screenshot({ type: "png" });
await browser.close();

const out = fileURLToPath(new URL("../src/preview/data.js", import.meta.url));
writeFileSync(
  out,
  `// GENERATED by scripts/build-preview.mjs: do not edit.\n// The 1200x630 PNG shown in link previews of the sign-in page, as base64 (a Worker has no file system).\n\nexport const PREVIEW_PNG = "${png.toString("base64")}";\n`
);
console.log(`wrote ${out} (${png.length} bytes)`);
