#!/usr/bin/env bash
# Regenerates src/fonts/data.js, the fonts the sign-in page serves from /auth/fonts/.
#
# Needs node/npm and Python's fonttools + brotli (pip install fonttools brotli). The output is committed,
# so nothing here runs when the package is installed or used; this is for whoever updates the fonts.
#
#   Archivo       the display face, pinned to width 80 and weight 900 (the headline and the ticket's name)
#   Inter         body text, variable weight
#   JetBrains Mono  the small labels, variable weight
#
# All three are SIL OFL 1.1 (see src/fonts/LICENSES.md), subset to Basic Latin, Latin-1 and a few
# punctuation marks. Text outside that range falls back to the system font.
#
# Archivo comes out different byte for byte on every run (the instancer stamps a modified time into
# it); the rendering is the same, and the file name's fingerprint changes with it, which is harmless.
set -euo pipefail
cd "$(dirname "$0")/.."
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
unicodes="U+0020-007E,U+00A0-00FF,U+2013,U+2014,U+2018-201D,U+2022,U+2026,U+2192,U+2197"

fetch() { (cd "$work" && npm pack "$1" --silent >/dev/null && mkdir -p "$2" && tar xzf ./*"$3"*.tgz -C "$2" && rm ./*.tgz); }
fetch @fontsource-variable/archivo archivo archivo
fetch @fontsource-variable/inter inter inter
fetch @fontsource-variable/jetbrains-mono mono jetbrains

fonttools varLib.instancer "$work/archivo/package/files/archivo-latin-wdth-normal.woff2" wght=900 wdth=80 -o "$work/archivo.ttf"
pyftsubset "$work/archivo.ttf" --unicodes="$unicodes" --flavor=woff2 --layout-features='kern,liga,calt' --output-file="$work/archivo-display.woff2"
pyftsubset "$work/inter/package/files/inter-latin-wght-normal.woff2" --unicodes="$unicodes" --flavor=woff2 --layout-features='kern,liga,calt,tnum' --output-file="$work/inter.woff2"
pyftsubset "$work/mono/package/files/jetbrains-mono-latin-wght-normal.woff2" --unicodes="$unicodes" --flavor=woff2 --layout-features='kern' --output-file="$work/jetbrains-mono.woff2"

{
  echo "// GENERATED by scripts/build-fonts.sh: do not edit. SIL Open Font License 1.1, see LICENSES.md."
  echo "// Base64 woff2, because a Worker has no file system and this package has no build step."
  echo
  echo "export const FONT_DATA = {"
  for name in archivo-display inter jetbrains-mono; do
    echo "  \"$name\": \"$(base64 -w0 "$work/$name.woff2")\","
  done
  echo "};"
} > src/fonts/data.js
ls -l src/fonts/data.js
